user=input("what is your name?")
print("snehal",user)
name=input("what is your father name")
print("bapu",name)
name=input("what is your best friend name")
print("pragati",name)
name=input("what is your education")
print("diploma",name)
name=input("what is your hobby")
print("dance",name)
